name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Format Check
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Type Check
        run: deno check src

      - name: Run Tests
        run: deno task test
